services:
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: beckdash
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .  # Change from ./server to . (root)
      dockerfile: server/Dockerfile.dev  # Specify full path to Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/beckdash
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=development_jwt_secret_key_replace_in_production
      - JWT_EXPIRES_IN=1h
      - REFRESH_TOKEN_SECRET=development_refresh_secret_key_replace_in_production
      - REFRESH_TOKEN_EXPIRES_IN=7d
      - PORT=3000
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3000/api/v1
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data: